### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by Mesqalito** [minman/browse-word-at-caret#39]
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'browsewordatcaret.BWACToggleActionAutoHighlight' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: BrowseWordAtCaret]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:201)

**Comment by C-Nedelcu** [comment]
Hello,

I'd like to report that I am running into the same problem.

Since updating PHPStorm to the latest version which is 2024.2.3, I'm getting an error popup when I start PHPStorm:

![image](https://github.com/user-attachments/assets/7992bfa8-0dc5-403c-9f60-d12e2f063087)

com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'browsewordatcaret.BWACToggleActionAutoHighlight' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: BrowseWordAtCaret]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:201)

This is not really an error, more like a deprecation warning. 
I've not seen any particular issues with the plugin itself so far.

**Comment by lemon-juice** [comment]
Same error in my case in PhpStorm 2024.2.1. Is this plugin still maintained? There have been no updates for more than 3 years.

**Comment by minman** [comment]
Yes, it's still maintained. There hasn't been a need for updates, but I will resolve the deprecations soon and make a new release.
